name: sample_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.3.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.10.0
  firebase_auth: ^4.8.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  fl_chart: ^0.68.0
  image_picker: ^0.8.4+4
  auto_size_text: ^3.0.0
  google_sign_in: ^5.2.1
  googleapis: ^10.0.0
  googleapis_auth: ^1.4.1
  http: ^0.13.4
  razorpay_flutter: ^1.3.7
  percent_indicator: ^4.2.3
#  package_info_plus_windows:
#    path: local_packages/package_info_plus_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
